openapi: 3.0.1
info:
  title: Paramatic API
  version: "1.0"
paths:
  /posts:
    get:
      security:
        - bearerAuth: []
      x-amazon-apigateway-integration:
        type: "MOCK"
        requestTemplates:
          application/json: |
            { "statusCode": 200 }
        responses:
          default:
            statusCode: "200"
    post:
      security:
        - bearerAuth: []
      x-amazon-apigateway-integration:
        type: "MOCK"
        requestTemplates:
          application/json: |
            { "statusCode": 201 }
        responses:
          default:
            statusCode: "201"

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        type: token
        authorizerUri: ${authorizer_uri}
        authorizerResultTtlInSeconds: 300
