openapi: 3.0.1
info:
  title: Paramatic API
  version: "1.0"
servers:
  - url: https://{restApiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      restApiId:
        default: ""
      region:
        default: "us-east-2"
      stage:
        default: "dev"

paths:
  /posts:
    get:
      security:
        - bearerAuth: []
      x-amazon-apigateway-integration:
        uri: "http://localhost:5217/api/posts"
        type: HTTP
        httpMethod: GET
        connectionType: INTERNET
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        requestParameters:
          integration.request.header.Accept: "'application/json'"
          integration.request.header.Content-Type: "'application/json'"
        responses:
          default:
            statusCode: "200"
      responses:
        "200":
          description: Success
    post:
      security:
        - bearerAuth: []
      x-amazon-apigateway-integration:
        uri: "http://localhost:5217/api/posts"
        type: HTTP
        httpMethod: POST
        connectionType: INTERNET
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        requestParameters:
          integration.request.header.Accept: "'application/json'"
          integration.request.header.Content-Type: "'application/json'"
        responses:
          default:
            statusCode: "201"
      responses:
        "201":
          description: Created

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        type: token
        authorizerUri: ${authorizer_uri}
        authorizerResultTtlInSeconds: 300
        identitySource: method.request.header.Authorization